<div id="wrapper">
 <div id="page-wrapper">
  <div class="row">
   <div class="col-lg-12">
    <script type="text/javascript">
        var randomnb = function(){ return Math.round(Math.random()*300)};
    </script>
    <div class="box">
     <h1>Chart.js - criando gráficos com a biblioteca Chart.js - DEMO</h1>
     <small>Arquivo com testes e demo de funcionalidades da biblioteca
      Chart.js criado para o tutorial do blog Web Social Dev.</small>

     <h2>Gráfico Pizza</h2>
     <small>Dados gerados com função javascript para números randômicos
      até 300.</small>

     <div class="box-chart">

      <canvas id="GraficoPizza" style="width: 100%;"></canvas>

      <script type="text/javascript">

                var options = {
                    responsive:true
                };

                var data = [
                    {
                        value: randomnb(),
                        color:"#F7464A",
                        highlight: "#FF5A6E",
                        label: "Vermelho"
                    },
                    {
                        value: randomnb(),
                        color:"#F7464A",
                        highlight: "#FF5A3E",
                        label: "Vermelho"
                    },
                    {
                        value: randomnb(),
                        color:"#F7464A",
                        highlight: "#FF5A8E",
                        label: "Vermelho"
                    },
                    {
                        value: randomnb(),
                        color:"#F7464A",
                        highlight: "#FF5A5A",
                        label: "Vermelho"
                    },
                    {
                        value: randomnb(),
                        color: "#46BFBD",
                        highlight: "#5AD3D1",
                        label: "Verde"
                    },
                    {
                        value: randomnb(),
                        color: "#FDB45C",
                        highlight: "#FFC870",
                        label: "Amarelo"
                    }
                ]
                
                window.onload = function(){

                    var ctx = document.getElementById("GraficoPizza").getContext("2d");
                    var PizzaChart = new Chart(ctx).Pie(data, options);
                }  
            </script>
     </div>

    </div>
   </div>
   <!-- /.col-lg-12 -->
  </div>
  <!-- /.row -->
  <div class="row">
   <div class="col-lg-6">
    <div class="panel panel-default">
     <div class="panel-heading">Area Chart Example</div>
     <!-- /.panel-heading -->
     <div class="panel-body">
      <div id="morris-area-chart"></div>
     </div>
     <!-- /.panel-body -->
    </div>
    <!-- /.panel -->
   </div>
   <!-- /.col-lg-6 -->
   <div class="col-lg-6">
    <div class="panel panel-default">
     <div class="panel-heading">Bar Chart Example</div>
     <!-- /.panel-heading -->
     <div class="panel-body">
      <div id="morris-bar-chart"></div>
     </div>
     <!-- /.panel-body -->
    </div>
    <!-- /.panel -->
   </div>
   <!-- /.col-lg-6 -->
   <div class="col-lg-6">
    <div class="panel panel-default">
     <div class="panel-heading">Line Chart Example</div>
     <!-- /.panel-heading -->
     <div class="panel-body">
      <div id="morris-line-chart"></div>
     </div>
     <!-- /.panel-body -->
    </div>
    <!-- /.panel -->
   </div>
   <!-- /.col-lg-6 -->
   <div class="col-lg-6">
    <div class="panel panel-default">
     <div class="panel-heading">Donut Chart Example</div>
     <!-- /.panel-heading -->
     <div class="panel-body">
      <div id="morris-donut-chart"></div>
     </div>
     <!-- /.panel-body -->
    </div>
    <!-- /.panel -->
   </div>
   <!-- /.col-lg-6 -->
   <div class="col-lg-12">
    <div class="panel panel-default">
     <div class="panel-heading">Morris.js Usage</div>
     <!-- /.panel-heading -->
     <div class="panel-body">
      <p>
       Morris.js is a jQuery based charting plugin created by Olly
       Smith. In SB Admin, we are using the most recent version of
       Morris.js which includes the resize function, which makes the
       charts fully responsive. The documentation for Morris.js is
       available on their website, <a target="_blank"
        href="http://morrisjs.github.io/morris.js/">http://morrisjs.github.io/morris.js/</a>.
      </p>
      <a target="_blank" class="btn btn-default btn-lg btn-block"
       href="http://morrisjs.github.io/morris.js/">View Morris.js
       Documentation</a>
     </div>
     <!-- /.panel-body -->
    </div>
    <!-- /.panel -->
   </div>
   <!-- /.col-lg-6 -->
  </div>
  <!-- /.row -->
 </div>
 <!-- /#page-wrapper -->

</div>
<!-- /#wrapper -->

